version: '3.7'

services:
  minimal:
    container_name: minimal
    build: 
      context: ./
    command: python minimal.py runserver 0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
volumes:
  pgdata:
