services:
  minimal:
    container_name: core
    build: 
      context: ./core
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./core:/home/core
    depends_on: 
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
