version: '3.7'

services:
  minimal:
    build: 
      context: ./
    command: python minimal.py runserver 0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    depends_on: 
      - postgres
  postgres:
    image: postgres:11.2-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432
volumes:
  pgdata:
